### ISSUE TITLE
OCR 接口报错

### ISSUE THREAD

**Issue by yangkghjh** [MT-Photos/mt-photos-ai#2]
版本：

```
MT Photos V1.23.0
mtphotos-ai:
  Image ID:       docker.io/mtphotos/mt-photos-ai@sha256:55a44340a964a472e48d570ed92508f10bf3139d4eaf71a01d14a01fa5623f7b
```

运行环境

```
k3s v1.24.3+k3s1
```

Trace 信息：

```log
INFO:     127.0.0.1:44206 - "POST /ocr HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/base.py", line 108, in __call__
    response = await self.dispatch_func(request, call_next)
  File "/app/server.py", line 55, in check_activity
    response = await call_next(request)
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/base.py", line 84, in call_next
    raise app_exc
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.8/dist-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/usr/local/lib/python3.8/dist-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 273, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 190, in run_endpoint_function
    return await dependant.call(**values)
  File "/app/server.py", line 121, in process_image
    _result = rapid_ocr(img)
  File "/usr/local/lib/python3.8/dist-packages/rapidocr_openvino/rapid_ocr_api.py", line 74, in __call__
    dt_boxes, det_elapse = self.text_detector(img)
  File "/usr/local/lib/python3.8/dist-packages/rapidocr_openvino/ch_ppocr_v3_det/text_detect.py", line 68, in __call__
    preds = self.infer(img)
  File "/usr/local/lib/python3.8/dist-packages/rapidocr_openvino/utils.py", line 30, in __call__
    self.session.infer(inputs=[input_content])
  File "/opt/intel/openvino/python/python3.8/openvino/runtime/ie_api.py", line 74, in infer
    return OVDict(super().infer(_data_dispatch(
RuntimeError: Check 'false' failed at src/inference/src/infer_request.cpp:215:
Reduce node with name 'p2o.GlobalAveragePool.10' has not found jit_uni_reduce_post_kernel_f32.


During handling of the above exception, another exception occurred:

  + Exception Group Traceback (most recent call last):
  |   File "/usr/local/lib/python3.8/dist-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
  |     result = await app(  # type: ignore[func-returns-value]
  |   File "/usr/local/lib/python3.8/dist-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
  |     return await self.app(scope, receive, send)
  |   File "/usr/local/lib/python3.8/dist-packages/fastapi/applications.py", line 292, in __call__
  |     await super().__call__(scope, receive, send)
  |   File "/usr/local/lib/python3.8/dist-packages/starlette/applications.py", line 122, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/errors.py", line 184, in __call__
  |     raise exc
  |   File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/errors.py", line 162, in __call__
  |     await self.app(scope, receive, _send)
  |   File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/base.py", line 110, in __call__
  |     response_sent.set()
  |   File "/usr/local/lib/python3.8/dist-packages/anyio/_backends/_asyncio.py", line 664, in __aexit__
  |     raise BaseExceptionGroup(
  | exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/usr/local/lib/python3.8/dist-packages/anyio/streams/memory.py", line 97, in receive
    |     return self.receive_nowait()
    |   File "/usr/local/lib/python3.8/dist-packages/anyio/streams/memory.py", line 92, in receive_nowait
    |     raise WouldBlock
    | anyio.WouldBlock
    |
    | During handling of the above exception, another exception occurred:
    |
    | Traceback (most recent call last):
    |   File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/base.py", line 78, in call_next
    |     message = await recv_stream.receive()
    |   File "/usr/local/lib/python3.8/dist-packages/anyio/streams/memory.py", line 112, in receive
    |     raise EndOfStream
    | anyio.EndOfStream
    |
    | During handling of the above exception, another exception occurred:
    |
    | Traceback (most recent call last):
    |   File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/base.py", line 108, in __call__
    |     response = await self.dispatch_func(request, call_next)
    |   File "/app/server.py", line 55, in check_activity
    |     response = await call_next(request)
    |   File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/base.py", line 84, in call_next
    |     raise app_exc
    |   File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/base.py", line 70, in coro
    |     await self.app(scope, receive_or_disconnect, send_no_error)
    |   File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/exceptions.py", line 79, in __call__
    |     raise exc
    |   File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/exceptions.py", line 68, in __call__
    |     await self.app(scope, receive, sender)
    |   File "/usr/local/lib/python3.8/dist-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    |     raise e
    |   File "/usr/local/lib/python3.8/dist-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    |     await self.app(scope, receive, send)
    |   File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 718, in __call__
    |     await route.handle(scope, receive, send)
    |   File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 276, in handle
    |     await self.app(scope, receive, send)
    |   File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 66, in app
    |     response = await func(request)
    |   File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 273, in app
    |     raw_response = await run_endpoint_function(
    |   File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 190, in run_endpoint_function
    |     return await dependant.call(**values)
    |   File "/app/server.py", line 121, in process_image
    |     _result = rapid_ocr(img)
    |   File "/usr/local/lib/python3.8/dist-packages/rapidocr_openvino/rapid_ocr_api.py", line 74, in __call__
    |     dt_boxes, det_elapse = self.text_detector(img)
    |   File "/usr/local/lib/python3.8/dist-packages/rapidocr_openvino/ch_ppocr_v3_det/text_detect.py", line 68, in __call__
    |     preds = self.infer(img)
    |   File "/usr/local/lib/python3.8/dist-packages/rapidocr_openvino/utils.py", line 30, in __call__
    |     self.session.infer(inputs=[input_content])
    |   File "/opt/intel/openvino/python/python3.8/openvino/runtime/ie_api.py", line 74, in infer
    |     return OVDict(super().infer(_data_dispatch(
    | RuntimeError: Check 'false' failed at src/inference/src/infer_request.cpp:215:
    | Reduce node with name 'p2o.GlobalAveragePool.10' has not found jit_uni_reduce_post_kernel_f32.
    |
    +------------------------------------
```

**Comment by yangkghjh** [comment]
CPU 不支持 avx2，更换后解决
